scitools-classroom/courses

- course_content/notebooks/iris_intro.ipynb
- course_content/notebooks/numpy_intro.ipynb
- make.sh
Deal with image sources in static html output by stripping `../files` from `<img>` tags by streaming the html output through a sed command.
This issue occurs when the `<img>` tag has been generated from a local image added to the notebook being converted. In the notebook this is referred to with a relative filepath of style `../files/path/to/img.png`, which is duplicated into the html. While this path works in the notebook it does not work in the html, due to the `files/` element of the path. The sed command introduced here strips out this section of the filepath, leaving `../path/to/img.png`.
> Correct image sources

- make.sh
Stop the make script from removing all output from the solutions notebooks for the build branch.
> Built solutions: retain output

- course_content/notebooks/numpy_intro.ipynb
We recently updated the approach used to define the values used in NP exercise two. This means there are now **11** values that the trapezoidal integral is calculated with. This means there are **10** values representing `x_i` and `x_i-1`, rather than 9 values, as was previously true.
That's all this PR changes.
> Correct single value in NP exercise 2 words

- course_content/notebooks/iris_intro.ipynb
- course_content/notebooks/matplotlib_intro.ipynb
- course_content/notebooks/numpy_intro.ipynb
While I was preparing #34 I noticed that there isn't a common style for introducing exercises in the four SciTools courses. This PR tackles that and in doing so proposes a common style to adopt for courses exercises.
----
The common style I've proposed here is:
* All exercises are introduced with "Exercise _n_", as an **h3**, with no trailing colon. For example:
* If the exercise contains multiple parts, each part should be introduced with the appropriate part number followed by a period (and a forward-slash in the markdown to prevent the markdown being interpreted as an ordered list element). For example:
2\. Description for the part of the exercise here:
* If the exercise is a final exercise (only matplotlib doesn't have one), each part should be introduced by **Part _n_** and a blank …
> Common styling for exercises

- course_content/notebooks/numpy_intro.ipynb
Adds links to the NumPy docs for the concepts listed in _§Further Reading_ at the end of the workshop material. Replaces #63.
> Links for further reading section

- course_content/notebooks/numpy_intro.ipynb
Any html document may have one `<h1>` tag and one only, for reasons of accessibilty. This removes all `<h1>` tags apart from the first and also reduces any sub-headers under the spurious `<h1>` tags so that consistency of header level is maintained.
> Reduce some header levels

- course_content/notebooks/cartopy_intro.ipynb
- course_content/notebooks/iris_intro.ipynb
- course_content/notebooks/matplotlib_intro.ipynb
You can't do
$ jupyter notebook --matplotlib=inline 
like you can do with ipython so we need to add the matplotlib magic to make the plots inline
So you can see what it looks like,
Here is matplotlib:
Here is cartopy:
Here is iris:
> Add %matplotlib=inline to notebooks with plots.

- course_content/notebooks/numpy_intro.ipynb
this example caused problems in the last running of the numpy course
the logic did not quite flow and it ended up confusing rather than illustrating the point
I have just removed it, as the simplest quick solution
> remove extension, did not flow for participants

- course_content/notebooks/numpy_intro.ipynb
Shorten the statistics section of the NumPy course, primarily by removing the first, and largely excessive, exercise. The key points of this exercise are ported into the final exercise in the section on Statistics, which is now the only exercise in this section.
> [NumPy] Shorten statistics section

- course_content/notebooks/numpy_intro.ipynb
Reinstates the section on the NumPy functionality `meshgrid` from the original NumPy course as `meshgrid` is required teaching of this course: it's used in the cartopy exercise.
> [NumPy] Reinstate section on meshgrid

- course_content/notebooks/cartopy_intro.ipynb
One of the pre-course requests from the target learners of the one-day course is an item on how to use matplotlib subplots. This adds a short section demonstrating using subplots within the context of comparing multiple cartopy map projections.
> [cartopy] Add item on subplots

- course_content/notebooks/cartopy_intro.ipynb
Added aims and objectives for the cartopy course to the top of the course. Also added section headings as they made it flow better once the aims and objectives section had been added.
Ping @benclarke18 @sophieallan
> [cartopy] Aims, objectives and section headings

- README.md
Add a link to the new dask course notebook as rendered on nbviewer.ipython.org.
> [dask] New course link in README

- course_content/notebooks/dask_intro.ipynb
Adds a section to the dask_intro notebook outlining how to use the `map` and `filter` functionality of `dask.bag` to constrain the cubes loaded using `iris.load` based on a phenomenon.
> [Dask] Add section on using map and filter to constrain iris.load

- course_content/notebooks/numpy_intro.ipynb
The previous change to the NumPy notebook accidentally resulted in invalid notebook json (inline double-quotes that were not escaped), which this change fixes.
> Fix NumPy notebook

- course_content/notebooks/numpy_intro.ipynb
Reinstates the 2D list used as a comparison to a 2D array in §Indexing. Also adds missing brackets around print statements.
> [NumPy] Code cell corrections

- course_content/notebooks/numpy_intro.ipynb
Shorten the NumPy course by removing the "observing site" content. Good as this content was for making NumPy real-world applicable, in practice it just made the course too long to teach. As such, I've stripped the content out but retained the generic teaching embedded in the content.
> Shorten NumPy course

- README.md
- environment.yml
- requirements.txt
Currently the links in README.md only point to a static html version of the notebooks using nbviewer.
This PR adds an `environment.yml` to allow Binder to create a Docker image from which to run the notebooks. These are fully interactive and editable so that those wishing to learn from the courses can do so without having to worry about setting up and running the notebooks on a local machine.
> Host notebooks on BinderHub

- README.md
- environment.yml
Since numpy 1.16, we need Iris 2.2.1 so that the iris course code can load PP data successfully.
It seems this is struggling to resolve an env since the availablility of builds with Python3.7 (probably the matplotlib builds ?), so the latest Iris (2.2.1) is not installed + errors occur running in Binder.
Pinning Python seems the simplest way to fix this for now.
Also removed various dependencies that are implied by Iris itself.
> Fix dependencies for Binder

- README.md
It looks to me as if _Cartopy in a Nutshell_ doesn't exist any more.  So the Iris course prerequisite should be _A First Look at Cartopy_.
> Update cartopy course name
