- course_content/numpy_intro.ipynb
A few improvements to the NumPy intro course, primarily to improve the readability of the markdown that contextualises the example Python code. This is intended to help when this course is used as a read resource rather than a taught resource.
> Wording improvements to NumPy intro course

- course_content/matplotlib_intro.ipynb
Some improvements to the words for the matplotlib course. It is hoped that these changes will make the course more useful as a read resource as well as a taught resource.
The biggest changes are the changes I've made to the wording of the last section on **savefig and backends**.
> Wording improvements for the matplotlib course

- course_content/iris_intro.ipynb
- course_content/matplotlib_intro.ipynb
- course_content/numpy_intro.ipynb
Prevents long lines of code disappearing off the right hand side of the screen when presenting the courses at high zoom on a low resolution screen.
> Shorten long lines in code cells

- .travis.yml
- make.sh
Builds the course content on submitting a PR to this repo. This means that the built content will not go stale compared to the source IPython notebooks. The built content is committed to the `build` branch of this repo.
The following items are built:
* static html copies of the source IPython notebooks (with code cell output but no exercise solutions),
* IPython notebooks to teach from (with no cell output or exercise solutions), and
* exercise solutions (with cell output and exercise solutions).
> Add Travis builds

- make.sh
Clean the build branch before each run and pull in common files (`README`, `LICENSE` and `.gitignore`). This ensures that these files are kept up-to-date with the master branch and that spurious files are not retained within the build branch.
> Clean build branch

- course_content/solutions/numpy_exercise_1.ipynb
- course_content/solutions/numpy_exercise_2.ipynb
As per the updates to the Cartopy solutions in #20.
> Updates to NumPy exercise solutions

- course_content/notebooks/matplotlib_intro.ipynb
- course_content/solutions/matplotlib_exercise_2.ipynb
- course_content/solutions/matplotlib_exercise_3.ipynb
Updates to tidy the solutions to the matplotlib exercises. Also includes one line's worth of change to the matplotlib course itself, which changes "Task 3" to the more appropriate "Exercise 3".
> Updates to matplotlib exercises solutions

- course_content/notebooks/matplotlib_intro.ipynb
This one-character* change demonstrates an almost embarrassing level of pedantry. Nonetheless, I spotted it and it annoyed me, so I've fixed it.
\* "Lets" --> "Let's".
> Updates to matplotlib course

- course_content/notebooks/numpy_intro.ipynb
Some improvements to the NumPy course. Includes:
* Changing the `x` values used in the final exercise (see also #26).
* Changing the values used in &sect;Slices so that the values are not the same as the indexes.
> NumPy course improvements

- course_content/notebooks/iris_intro.ipynb
Fixes a few niggles with the Iris course materials. Specifically, the things fixed are the three outstanding items from #28, and a little bit of tidying of the markdown sections surrounding these outstanding items.
> Tidying some Iris course niggles

- course_content/notebooks/numpy_intro.ipynb
> Numpynewintro

- course_content/notebooks/numpy_intro.ipynb
**Not really ready to merge**
Banking some work in progress from today:
* vectorisation and efficiency sections from @marqh 
* a start on the "Stats + Masking" section from @pp-mo
> Numpy stats

- course_content/notebooks/numpy_intro.ipynb
I've made a number of reasonably minor changes to the wording of the document. The content looks sound though!
Things of note:
* paragraphs or lots of one sentence per line? We have examples of both. My preference is toward using paragraphs as paragraphs and only using sentence-per-line to really emphasize something.
* Consistency: `NumPy` or `numpy`? We have examples of both, but should fix on one. My preference is for `NumPy`, as that is the actual name of the project and how it is always self-referenced in its own documentation.
* Consistency: do we want a space preceding an item of punctuation or not? I don't (see the end of the previous sentence!) but I know @pp-mo does. We should agree on one and stick to it (and I don't mind which we choose).
* Consistency: header levels. We should …
> Check wording of existing content

- course_content/notebooks/numpy_intro.ipynb
> return trapezoidal exercise

- course_content/notebooks/numpy_intro.ipynb
summaries and content review
@marqh and @pp-mo
> summaries and review

- course_content/notebooks/numpy_intro.ipynb
Lifts an exercise on broadcasting from the original NumPy course and adds it to the new one.
> Extra broadcasting exercise

- course_content/notebooks/numpy_intro.ipynb
Maybe this is a more helpful way of showing how broadcasting works in each case.
> Print shapes in broadcasting example

- course_content/notebooks/numpy_intro.ipynb
Rearrange a few concepts so they are introduced and discussed before other parts of the course needs them. Also ensures the final exercise is the final element of the course other than the further reading.
> [NumPy] Rearrange some concepts

- course_content/notebooks/cartopy_intro.ipynb
Add the word "degrees" to the exercise introduction for the sake of numerical units and improved readability.
> [cartopy] Add word to exercise intro

- course_content/notebooks/numpy_intro.ipynb
Incremental updates to the NumPy course.
> [NumPy] Updates July 2017

- course_content/notebooks/brief_iris_intro.ipynb
Replaces #97, which somehow was referencing the wrong branch...
> A shorter Iris course

- course_content/notebooks/brief_iris_intro.ipynb
Changed air_temperature.pp file name to air_temp.pp
> Changed air_temp filename

- course_content/notebooks/numpy_intro.ipynb
Some of the exercises in the new NumPy course are difficult to use as what is expected from the exercise is not clear as the scope of the exercises is too broad. This makes them hard to teach and less beneficial to learners than they could be.
The changes here tighten the scope of each of these exercises so that what is expected of the learners is much more clear.
> [NumPy] Accessible exercises

- course_content/notebooks/dask_intro.ipynb
Ignoring the noise of the notebook diff, this PR makes the review changes suggested to #107. These are a few minor changes to some bits of text and code content. This PR does _not_ address the more complex questions about [ordering of content](https://github.com/SciTools/courses/pull/107#pullrequestreview-100121064) or [delaying the merge operation](https://github.com/SciTools/courses/pull/107#pullrequestreview-101003572).
> [dask] Updates to "Iris Load with dask" section

- .travis.yml
- README.md
This PR makes some minor changes to the rendered URLs for the notebooks in the `README.md`.
> alias ugly urls

- make.sh
This PR updates the HTML maker to include the `dask_intro` notebook.
> fix make.sh

- course_content/notebooks/dask_intro.ipynb
Adds an exercise at the end of the section on parallel loading files in Iris using dask.
> [dask] Add loading exercise

- .travis.yml
Attempt to fix build uploading ...
> fix build upload

- course_content/notebooks/dask_intro.ipynb
Here is some draft content on the rationale for this course: why it exists and what it intends to teach. It is very much still a **draft** however -- there may even still be typos -- so go easy on the review!
> [dask] Course rationale

- course_content/notebooks/numpy_intro.ipynb
Updates to the section on Indexing, including ellipsis (a pre-requisite for the Iris course) and the concept of slicing. I've also slimmed one of the code examples and updated the section summary.
> [NumPy] Updates for §Indexing

- course_content/notebooks/numpy_intro.ipynb
Adds learning outcomes (i.e. objectives) to each top-level section within the NumPy course. Also makes sure the section on aims at the start of the course lays out the course aims.
> [NumPy] Aims and objectives

- course_content/notebooks/matplotlib_intro.ipynb
Adds learning outcomes to each section of the matplotlib course, as well as a high-level aim for the course overall. Also tidies a few annoying niggles with the course content.
> Learning outcomes for matplotlib course

- course_content/notebooks/iris_intro.ipynb
- course_content/notebooks/matplotlib_intro.ipynb
Checked all four notebooks with Python3 + Iris2. All changes are to ensure compatibility. Only outstanding incompatibilities are four warnings, which will be detailed below.
> Python3 & Iris2 compatibility check

- course_content/notebooks/numpy_intro.ipynb
Changes to the NumPy course based on the recent run of the course.
Ping @corinnebosley @kaedonkers
> NumPy course changes, May 2018

- course_content/notebooks/numpy_intro.ipynb
Improve a few sections of the NumPy course - correcting a couple of typos, clarifying one exercise, and adding a couple of missing doc links.
> NumPy course updates, July 2018

- course_content/notebooks/iris_intro.ipynb
A few tidies of the Iris course, lost amongst changes in the underlying JSON...
> Iris course updates

- course_content/notebooks/iris_course/0.Iris_Course_Intro.ipynb
- course_content/notebooks/iris_course/1.The_Iris_Cube.ipynb
- course_content/notebooks/iris_course/2.Loading_and_Saving.ipynb
- course_content/solutions/iris_exercise_1
- course_content/solutions/iris_exercise_2
This is to replace #148 and pull together various changes from @lbdreyer and myself
On feature branch, I will self-merge !!
> Split Iris course into multiple notebooks and improve first 2 sections

- course_content/iris_course/1.The_Iris_Cube.ipynb
Remaining review suggestions from #151
> Leftover review changes from #151.

- README.md
- course_content/cartopy_course/cartopy_intro.ipynb
This is my suggestion for more "general users context".
> Fuller usage context in readme.

- course_content/iris_course/3.Subcube_Extraction.ipynb
- course_content/iris_course/solutions/iris_exercise_3.1a
A few readability and language tweaks.
I _haven't_ changed the "Suggested Activity"s to "Exercise"s as it makes the diffs messy.
We can do that all in one later ?
> Small changes to Iris section 3.

- course_content/iris_course/1.The_Iris_Cube.ipynb
- course_content/iris_course/2.Loading_and_Saving.ipynb
- course_content/iris_course/3.Subcube_Extraction.ipynb
- course_content/iris_course/4.Joining_Cubes_Together.ipynb
- course_content/iris_course/6.Data_Processing.ipynb
Lots of trivial changes.
I've mostly left alone sections that are still being worked on.
> Rationalised exercise formatting and removed all outputs.

- course_content/iris_course/5.Cube_Plotting.ipynb
A few little things that were missing from the plotting section of the Iris course:
* Updates the numbering of the headers `4.1 -> 5.1`
* Adds a learning outcome at the top
* Adds a summary at the bottom
* Adds a table of contents.
> Minor fixes to the plotting section

- course_content/iris_course/0.Iris_Course_Intro.ipynb
- course_content/iris_course/2.Loading_and_Saving.ipynb
- course_content/iris_course/7.Advanced_Concepts.ipynb
- course_content/iris_course/8.Final_Exercise.ipynb
- course_content/iris_course/solutions/iris_exercise_7.2a
- course_content/iris_course/solutions/iris_exercise_7.3a
- course_content/iris_course/solutions/iris_exercise_8.1
- course_content/iris_course/solutions/iris_exercise_8.2
- course_content/iris_course/solutions/iris_exercise_8.3
- course_content/iris_course/solutions/iris_exercise_8.4
- course_content/iris_course/solutions/iris_exercise_8.5
- course_content/iris_course/solutions/iris_exercise_8.6
This updates the final section of the iris course. No particularly major changes in this PR. 
Summary of changes:
* Split out final exercise into its own notebook
* Moved the "Out of core processing" part from Section 2, Loading and Saving,  in to Section 7, Advance Concepts
* Removed the custom categorisation section from "Categorical Coordinates for Grouped Statistics" - the example it gives just wasn't very good and I don't think its necessary in this course
* Added two exercises.
* Note there is **no** "Section Review Exercise" for advanced concepts as its a bit hard to find a exercise that draws on all parts of the section, which is a bit of a ragbag of concepts.
> Update Advanced Concepts section, and split out final exercise

- course_content/iris_course/5.Cube_Plotting.ipynb
- course_content/iris_course/6.Data_Processing.ipynb
- course_content/iris_course/solutions/iris_exercise_6.1a
- course_content/iris_course/solutions/iris_exercise_6.1b
- course_content/iris_course/solutions/iris_exercise_6.1c
- course_content/iris_course/solutions/iris_exercise_6.1d
- course_content/iris_course/solutions/iris_exercise_6.1e
- course_content/iris_course/solutions/iris_exercise_6.1f
- course_content/iris_course/solutions/iris_exercise_6.2a
- course_content/iris_course/solutions/iris_exercise_6.3a
- course_content/iris_course/solutions/iris_exercise_6.3b
- course_content/iris_course/solutions/iris_exercise_6.3c
- course_content/iris_course/solutions/iris_exercise_6.3d
- course_content/iris_course/solutions/iris_exercise_6.3e
Rework of the maths + stats section.
> Maths improve

- course_content/iris_course/7.Advanced_Concepts.ipynb
A few odd things I thought needed improving.
> Miscellaneous wording improvements in section 7.

- course_content/iris_course/2.Loading_and_Saving.ipynb
- course_content/iris_course/3.Subcube_Extraction.ipynb
- course_content/iris_course/5.Cube_Plotting.ipynb
- course_content/iris_course/7.Advanced_Concepts.ipynb
- course_content/iris_course/solutions/iris_exercise_5.1d
Some more "final" (!) changes from a general re-read
This targets the feature branch, but I think we can safely wait until after #167, if wanted.
Note that it includes some changes for suggestions on #167 : https://github.com/SciTools/courses/pull/167#discussion_r279915474
> Odd final tweaks

- README.md
This is my final suggestion for an improvement that promotes our recommendations for learning the "other" packages.
As it happens, it came out really small 😉 
With this done, I for one am ready to merge back !
> Highlight learning requirements.

- README.md
> Tiny change, mostly for Binder update testing.

- README.md
Mostly follows suggestions from @tkknight
> Review changes: textflow; fix link to conda page.

- course_content/iris_course/3.Subcube_Extraction.ipynb
- course_content/iris_course/7.Advanced_Concepts.ipynb
- course_content/iris_course/solutions/iris_exercise_4.3.2b
- course_content/iris_course/solutions/iris_exercise_8.3
I have made some changes to the iris_course. Mainly to add some clarity to some of the solutions and to close an existing issue #175.
closes #175
> Scitools changes for added clarity
